services:
  frontend:
    build: .
    container_name: fish_farm_frontend
    command: npm run dev -- --webpack
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "1000"